language: r
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE"

repos:
  XRAN: https://xran.yihui.name

before_install:
  - "curl https://xran.yihui.org/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl https://xran.yihui.org/r-xran | bash)"
